# app/config/routing.yml
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

acme_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: AcmeDemoBundle:Security:login }

acme_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: AcmeDemoBundle:Security:loginCheck }

routea:
    pattern:  /index.html
    defaults: { _controller: AcmeDemoBundle:Welcome:index, name: 'routea' }

routeb:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

#routec:
#    pattern:  ///news///{year}///{category}
#    defaults: { _controller: AcmeDemoBundle:Welcome:index, name: 'routec' }

#routed:
#    pattern:  /{year}/news-about-{category}-happened-in-{year}
#    defaults: { _controller: AcmeDemoBundle:Security:loginCheck }

routee:
    pattern:  /{_locale}
    defaults: { _controller: AcmeDemoBundle:Security:loginCheck }

acme_api_articles:
    pattern:  /api/articles
    defaults: { _controller: AcmeDemoBundle:Api:articles }

acme_api_user:
    pattern:  /api/user
    defaults: { _controller: AcmeDemoBundle:Api:user }
