fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

stark_industries_iron_wall_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: StarkIndustriesIronWallBundle:Security:login }

stark_industries_iron_wall_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: StarkIndustriesIronWallBundle:Security:loginCheck }

stark_industries_api_articles:
    pattern:  /api/articles
    defaults: { _controller: StarkIndustriesIronWallBundle:Api:articles }

stark_industries_api_user:
    pattern:  /api/user
    defaults: { _controller: StarkIndustriesIronWallBundle:Api:user }
